"""add assignment association table

Revision ID: 89379b8c245b
Revises: 1b90f7c52544
Create Date: 2024-06-28 22:36:01.322283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89379b8c245b'
down_revision = '1b90f7c52544'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assigments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_assigments_employee_id_employees')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assigments')
    # ### end Alembic commands ###
